sudo: false
language: python
notifications:
  email:
    recipients:
      - frsy@vip.qq.com
    on_success: always
    on_failure: always
python:
  - "3.8"
  - "3.7"
  - "3.6"
before_install:
  - pip install -r requirements.txt
script:
  - python setup.py install